### ISSUE TITLE
installation failed giving permission error!

### ISSUE THREAD

**Issue by aviboy2006** [appcelerator/ioslib#114]
While installing 
`npm i -g ioslib`

Getting below error: 

```
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.

> node-ios-device@1.7.1 install /usr/local/lib/node_modules/ioslib/node_modules/node-ios-device
> node ./bin/run.js node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for node-ios-device@1.7.1 and node@10.19.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding' 
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/var/root/Library/Caches/node-gyp/10.19.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/.node-gyp'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64/node_ios_device.node" "--module_name=node_ios_device" "--module_path=/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/ioslib/node_modules/node-ios-device
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64/node_ios_device.node --module_name=node_ios_device --module_path=/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/ioslib/node_modules/node-ios-device
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64/node_ios_device.node --module_name=node_ios_device --module_path=/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-ios-device@1.7.1 install: `node ./bin/run.js node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-ios-device@1.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2020-04-14T18_58_32_296Z-debug.log
```

Tried giving permission also but not working.

**Comment by cb1kenobi** [comment]
Try `sudo npm install --unsafe-perm=true -g ioslib`.

**Comment by aviboy2006** [comment]
able to installed but getting this error : 

```
sh-3.2# ioslib reset-sims
sh: ioslib: command not found
```

**Comment by cb1kenobi** [comment]
`/usr/local/bin` may not be in your PATH. Try running it with an absolute path: `/usr/local/bin/ioslib reset-sims`.

**Comment by aviboy2006** [comment]
Got this response for installation : 

```
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.

> node-ios-device@1.7.1 install /usr/local/lib/node_modules/ioslib/node_modules/node-ios-device
> node ./bin/run.js node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[node-ios-device] Success: "/usr/local/lib/node_modules/ioslib/node_modules/node-ios-device/binding/node-v64-darwin-x64/node_ios_device.node" is installed via remote
+ ioslib@1.7.20
added 214 packages from 144 contributors in 6.271s
```

For running command
```
sh-3.2# /usr/local/bin/ioslib reset-sims
sh: /usr/local/bin/ioslib: No such file or directory
```

**Comment by cb1kenobi** [comment]
Oh snap! Sigh. So, the `latest` tag is associated to v1.7.20. The `ioslib` command was introduced in 2.x, but the latest is 3.2.5. In other words, you have the old version. Easy to fix:

```
sudo npm install --unsafe-perm=true -g ioslib@next
```

Then you should be able to simply run `ioslib reset-sims`.

**Comment by aviboy2006** [comment]
Thanks its works now! let me try my luck whether actual error is solved or not.
