### ISSUE TITLE
can't build when I clone down.

### ISSUE THREAD

**Issue by Sophrinix** [appcelerator/ioslib#15]
➜  Desktop  node -v
v0.10.13
➜  Desktop  git clone --recursive git@github.com:appcelerator/ioslib.git
Cloning into 'ioslib'...
remote: Counting objects: 594, done.
remote: Total 594 (delta 0), reused 0 (delta 0), pack-reused 594
Receiving objects: 100% (594/594), 304.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (350/350), done.
Checking connectivity... done.
➜  Desktop  cd ioslib
➜  ioslib git:(master) sudo npm install
npm WARN package.json ioslib@0.2.15 license should be a valid SPDX license expression

> node-ios-device@0.3.2 install /Users/andrewmcelroy/Desktop/ioslib/node_modules/node-ios-device
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/andrewmcelroy/Desktop/ioslib/node_modules/node-ios-device) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewmcelroy/Desktop/ioslib/node_modules/node-ios-device
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.13
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-ios-device@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-ios-device@0.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-ios-device package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-ios-device
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewmcelroy/Desktop/ioslib/npm-debug.log
➜  ioslib git:(master) node-gyp rebuild
zsh: command not found: node-gyp

**Comment by Sophrinix** [comment]
Then I realized I didn't have node-gyp installed. After I installed it I got this:

➜  ioslib git:(master) ✗ sudo npm install
npm WARN package.json ioslib@0.2.15 license should be a valid SPDX license expression
-
> node-ios-device@0.3.2 install /Users/andrewmcelroy/Desktop/ioslib/node_modules/node-ios-device
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/andrewmcelroy/Desktop/ioslib/node_modules/node-ios-device) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewmcelroy/Desktop/ioslib/node_modules/node-ios-device
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.13
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-ios-device@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-ios-device@0.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-ios-device package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-ios-device
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewmcelroy/Desktop/ioslib/npm-debug.log

**Comment by Sophrinix** [comment]
pull request coming. The out of date dependencies make this uninstallable. This impacts the tio2 project which I am trying to document.

**Comment by cb1kenobi** [comment]
@Sophrinix This should be fixed by https://github.com/appcelerator/ioslib/pull/14 once it's merged.

**Comment by hbugdoll** [comment]
Can be closed because https://github.com/tidev/ioslib/pull/14 was merged.
